### ISSUE TITLE
vagrant-omnibus gives error although correct proxy is set

### ISSUE THREAD

**Issue by jayrp11** [tmatilai/vagrant-proxyconf#134]
I have below plugins installed
```
C:\>vagrant plugin list
vagrant-berkshelf (4.0.4)
vagrant-ca-certificates (1.0.2)
vagrant-cachier (1.2.1)
vagrant-login (1.0.1, system)
vagrant-omnibus (1.4.1)
vagrant-proxyconf (1.5.1)
vagrant-share (1.1.4, system)
vagrant-vbguest (0.10.0)
```

In my Vagrantfile I have 
```
config.ca_certificates.enabled = true
config.ca_certificates.certs = Dir.glob('C:/ssl/*.crt')
config.omnibus.chef_version = :latest
```

And in global Vagrantfile
```
config.proxy.http     = "http://myproxy/"
config.proxy.https    = "http://myproxy/"
config.proxy.no_proxy = "localhost,127.0.0.1,.example.com"
```

While running the vagrant up first time I am getting below error
```
    Bringing machine 'default' up with 'virtualbox' provider...
    default: The Berkshelf shelf is at "H:/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150930-8216-1au7gvy-default"
==> default: Sharing cookbooks with VM
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: test_default_1443594532782_74213
==> default: Clearing any previously set forwarded ports...
==> default: Updating Vagrant's Berkshelf...
==> default: Resolving cookbook dependencies...
==> default: Fetching 'test' from source at chef/cookbooks/test
==> default: Using apache2 (3.1.0)
==> default: Using java (1.35.0)
==> default: Using test (0.1.0) from source at chef/cookbooks/test
==> default: Vendoring apache2 (3.1.0) to H:/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150930-8216-1au7gvy-default/apache2
==> default: Vendoring java (1.35.0) to H:/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150930-8216-1au7gvy-default/java
==> default: Vendoring test (0.1.0) to H:/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150930-8216-1au7gvy-default/test
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
==> default: Configuring proxy for Apt...
==> default: Configuring proxy for Chef provisioners...
==> default: Configuring proxy environment variables...
GuestAdditions versions on your host (4.3.6) and guest (4.3.10) do not match.
stdin: is not a tty
 * Stopping VirtualBox Additions
   ...done.
stdin: is not a tty
Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  dkms fakeroot gcc gcc-4.8 libasan0 libatomic1 libc-dev-bin libc6-dev
  libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libfakeroot libfontenc1
  libgcc-4.8-dev libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa libgomp1
  libice6 libitm1 libllvm3.4 libpciaccess0 libpixman-1-0 libquadmath0 libsm6
  libtsan0 libtxc-dxtn-s2tc0 libx11-xcb1 libxaw7 libxcb-dri2-0 libxcb-dri3-0
  libxcb-glx0 libxcb-present0 libxcb-sync1 libxcomposite1 libxdamage1
  libxfixes3 libxfont1 libxkbfile1 libxmu6 libxpm4 libxrandr2 libxrender1
  libxshmfence1 libxt6 libxxf86vm1 linux-libc-dev manpages-dev x11-common
  x11-xkb-utils xfonts-base xfonts-encodings xfonts-utils xserver-common
  xserver-xorg-core
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  virtualbox-guest-dkms* virtualbox-guest-utils* virtualbox-guest-x11*
0 upgraded, 0 newly installed, 3 to remove and 0 not upgraded.
After this operation, 12.1 MB disk space will be freed.
(Reading database ... 61001 files and directories currently installed.)
Removing virtualbox-guest-dkms (4.3.10-dfsg-1ubuntu5) ...

-------- Uninstall Beginning --------
Module:  virtualbox-guest
Version: 4.3.10
Kernel:  3.13.0-63-generic (x86_64)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

vboxguest.ko:
 - Uninstallation
   - Deleting from: /lib/modules/3.13.0-63-generic/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


vboxsf.ko:
 - Uninstallation
   - Deleting from: /lib/modules/3.13.0-63-generic/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


vboxvideo.ko:
 - Uninstallation
   - Deleting from: /lib/modules/3.13.0-63-generic/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod....

DKMS: uninstall completed.

------------------------------
Deleting module version: 4.3.10
completely from the DKMS tree.
------------------------------
Done.
Removing virtualbox-guest-x11 (4.3.10-dfsg-1ubuntu5) ...
Purging configuration files for virtualbox-guest-x11 (4.3.10-dfsg-1ubuntu5) ...
Removing virtualbox-guest-utils (4.3.10-dfsg-1ubuntu5) ...
Purging configuration files for virtualbox-guest-utils (4.3.10-dfsg-1ubuntu5) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
stdin: is not a tty
Reading package lists...
Building dependency tree...
Reading state information...
dkms is already the newest version.
dkms set to manually installed.
linux-headers-3.13.0-63-generic is already the newest version.
linux-headers-3.13.0-63-generic set to manually installed.
The following packages were automatically installed and are no longer required:
  libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libfontenc1 libgl1-mesa-dri
  libgl1-mesa-glx libglapi-mesa libice6 libllvm3.4 libpciaccess0 libpixman-1-0
  libsm6 libtxc-dxtn-s2tc0 libx11-xcb1 libxaw7 libxcb-dri2-0 libxcb-dri3-0
  libxcb-glx0 libxcb-present0 libxcb-sync1 libxcomposite1 libxdamage1
  libxfixes3 libxfont1 libxkbfile1 libxmu6 libxpm4 libxrandr2 libxrender1
  libxshmfence1 libxt6 libxxf86vm1 x11-common x11-xkb-utils xfonts-base
  xfonts-encodings xfonts-utils xserver-common xserver-xorg-core
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Copy iso file C:\Program Files\Oracle\VirtualBox\VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
stdin: is not a tty
mount: block device /tmp/VBoxGuestAdditions.iso is write-protected, mounting read-only
Installing Virtualbox Guest Additions 4.3.6 - guest version is 4.3.10
stdin: is not a tty
Verifying archive integrity... All good.
Uncompressing VirtualBox 4.3.6 Guest Additions for Linux............
VirtualBox Guest Additions installer
Copying additional installer modules ...
Installing additional modules ...
Removing existing VirtualBox DKMS kernel modules ...done.
Removing existing VirtualBox non-DKMS kernel modules ...done.
Building the VirtualBox Guest Additions kernel modules ...done.
Doing non-kernel setup of the Guest Additions ...done.
Starting the VirtualBox Guest Additions ...done.
Installing the Window System drivers ...fail!
(Could not find the X.Org or XFree86 Window System.)
An error occurred during installation of VirtualBox Guest Additions 4.3.6. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
stdin: is not a tty
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /var/www => C:/jdp/baps/lamp/test
    default: /vagrant => C:/jdp/baps/lamp/test
    default: /tmp/vagrant-cache => C:/Users/pateljd/.vagrant.d/cache/ubuntu/trusty64
    default: /tmp/vagrant-chef-3/chef-solo-1/cookbooks => H:/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150930-8216-1au7gvy-default
==> default: Installing Chef 12.4.3 Omnibus package...
==> default: Downloading Chef 12.4.3 for ubuntu...
==> default: downloading https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
==> default:   to file /tmp/install.sh.5643/metadata.txt
==> default: trying wget...
==> default: trying curl...
==> default: trying perl...
==> default: trying python...
==> default: Unable to retrieve a valid package!
==> default: Version: 12.4.3

==> default: Please file a Bug Report at https://github.com/opscode/opscode-omnitruck/issues/new
==> default: Alternatively, feel free to open a Support Ticket at https://www.getchef.com/support/tickets
==> default: More Chef support resources can be found at https://www.getchef.com/support

==> default: Please include as many details about the problem as possible i.e., how to reproduce
==> default: the problem (if possible), type of the Operating System and its version, etc.,
==> default: and any other relevant details that might help us with troubleshooting.

==> default: Metadata URL: https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
==> default:
==> default: DEBUG OUTPUT FOLLOWS:
==> default:
==> default: STDERR from wget:
==> default:
==> default: --2015-09-30 06:31:17--  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
==> default: Resolving www.getchef.com (www.getchef.com)... 103.245.222.65
==> default: Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
==> default: Retrying.
==> default:
==> default: --2015-09-30 06:33:30--  (try: 2)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
==> default: Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
==> default: Retrying.
==> default:
==> default: --2015-09-30 06:35:39--  (try: 3)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
==> default: Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
==> default: Retrying.
==> default:
==> default: --2015-09-30 06:37:50--  (try: 4)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
==> default: Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
==> default: Retrying.
==> default:
==> default: --2015-09-30 06:40:01--  (try: 5)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
==> default: Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
==> default: Retrying.
==> default:
==> default: --2015-09-30 06:42:13--  (try: 6)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
==> default: Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
==> default: Retrying.
==> default:
==> default: --2015-09-30 06:44:26--  (try: 7)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
==> default: Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
==> default: Retrying.
==> default:
==> default: --2015-09-30 06:46:41--  (try: 8)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
==> default: Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
==> default: Retrying.
==> default:
==> default: --2015-09-30 06:48:56--  (try: 9)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
==> default: Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
==> default: Retrying.
==> default:
==> default: --2015-09-30 06:51:12--  (try:10)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
==> default: Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
==> default: Retrying.
==> default:
==> default: --2015-09-30 06:53:29--  (try:11)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
==> default: Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
==> default: Retrying.
==> default:
==> default: --2015-09-30 06:55:47--  (try:12)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
==> default: Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
==> default: Retrying.
==> default:
==> default: --2015-09-30 06:58:04--  (try:13)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
==> default: Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
==> default: Retrying.
==> default:
==> default: --2015-09-30 07:00:21--  (try:14)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
==> default: Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
==> default: Retrying.
==> default:
==> default: --2015-09-30 07:02:38--  (try:15)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
==> default: Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
==> default: Retrying.
==> default:
==> default: --2015-09-30 07:04:56--  (try:16)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
==> default: Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
==> default: Retrying.
==> default:
==> default: --2015-09-30 07:07:13--  (try:17)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
==> default: Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
==> default: Retrying.
==> default:
==> default: --2015-09-30 07:09:30--  (try:18)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
==> default: Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
==> default: Retrying.
==> default:
==> default: --2015-09-30 07:11:47--  (try:19)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
==> default: Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
==> default: Retrying.
==> default:
==> default: --2015-09-30 07:14:04--  (try:20)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
==> default: Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
==> default: Giving up.
==> default:
==> default: STDERR from curl:
==> default:
==> default:
==> default:
==> default: STDERR from perl:
==> default:
==> default: Can't locate LWP/Simple.pm in @INC (you may need to install the LWP::Simple module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/s
hare/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at -e line 1.
==> default: BEGIN failed--compilation aborted at -e line 1.
==> default:
==> default: STDERR from python:
==> default:
==> default: Traceback (most recent call last):
==> default:   File "<string>", line 1, in <module>
==> default:   File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
==> default:     return _opener.open(url, data, timeout)
==> default:   File "/usr/lib/python2.7/urllib2.py", line 404, in open
==> default:     response = self._open(req, data)
==> default:   File "/usr/lib/python2.7/urllib2.py", line 422, in _open
==> default:     '_open', req)
==> default:   File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
==> default:     result = func(*args)
==> default:   File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
==> default:     return self.do_open(httplib.HTTPSConnection, req)
==> default:   File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
==> default:     raise URLError(err)
==> default: urllib2.URLError: <urlopen error [Errno 110] Connection timed out>
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

sh install.sh -v 12.4.3 -d /tmp/vagrant-cache/vagrant_omnibus 2>&1

Stdout from the command:

Downloading Chef 12.4.3 for ubuntu...
downloading https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
  to file /tmp/install.sh.5643/metadata.txt
trying wget...
trying curl...
trying perl...
trying python...
Unable to retrieve a valid package!
Version: 12.4.3

Please file a Bug Report at https://github.com/opscode/opscode-omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.getchef.com/support/tickets
More Chef support resources can be found at https://www.getchef.com/support

Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.

Metadata URL: https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64

DEBUG OUTPUT FOLLOWS:

STDERR from wget:

--2015-09-30 06:31:17--  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
Resolving www.getchef.com (www.getchef.com)... 103.245.222.65
Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
Retrying.

--2015-09-30 06:33:30--  (try: 2)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
Retrying.

--2015-09-30 06:35:39--  (try: 3)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
Retrying.

--2015-09-30 06:37:50--  (try: 4)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
Retrying.

--2015-09-30 06:40:01--  (try: 5)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
Retrying.

--2015-09-30 06:42:13--  (try: 6)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
Retrying.

--2015-09-30 06:44:26--  (try: 7)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
Retrying.

--2015-09-30 06:46:41--  (try: 8)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
Retrying.

--2015-09-30 06:48:56--  (try: 9)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
Retrying.

--2015-09-30 06:51:12--  (try:10)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
Retrying.

--2015-09-30 06:53:29--  (try:11)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
Retrying.

--2015-09-30 06:55:47--  (try:12)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
Retrying.

--2015-09-30 06:58:04--  (try:13)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
Retrying.

--2015-09-30 07:00:21--  (try:14)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
Retrying.

--2015-09-30 07:02:38--  (try:15)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
Retrying.

--2015-09-30 07:04:56--  (try:16)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
Retrying.

--2015-09-30 07:07:13--  (try:17)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
Retrying.

--2015-09-30 07:09:30--  (try:18)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
Retrying.

--2015-09-30 07:11:47--  (try:19)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
Retrying.

--2015-09-30 07:14:04--  (try:20)  https://www.getchef.com/chef/metadata?v=12.4.3&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
Connecting to www.getchef.com (www.getchef.com)|103.245.222.65|:443... failed: Connection timed out.
Giving up.

STDERR from curl:



STDERR from perl:

Can't locate LWP/Simple.pm in @INC (you may need to install the LWP::Simple module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /u
sr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at -e line 1.
BEGIN failed--compilation aborted at -e line 1.

STDERR from python:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>



Stderr from the command:
```

But just after that if I run vagrant provision it works fine meaning chef latest version is installed correctly and provision runs successfully. I have added some echo statements in [install.sh](https://www.getchef.com/chef/install.sh) and observed that environment proxy variables are not taking effect for first time. However, from second time onwards it is fine. 

I am not sure if this issue is reported earlier but did not find any record.

**Comment by tmatilai** [comment]
Hi,

I haven't tested the combination of vagrant-proxyconf and vagrant-omnibus for a long time, so it is possible things have broken e.g. due to changes in the omnibus installer (install.sh). I'll try to take a look on some point.

Btw, have you tried the built-in Chef installer in later Vagrant versions? See `install` and `version` in [the docs](https://docs.vagrantup.com/v2/provisioning/chef_common.html).

**Comment by codylane** [comment]
Hi - I've just release 2.0.1, which includes many fixes.  Please confirm this issue is resolved by installing 2.0.1.  If I don't hear from you in a couple weeks I'll go ahead and close this out.  

Thanks for reporting.
