### ISSUE TITLE
Proxy fails with ppa: URIs

### ISSUE THREAD

**Issue by chimericdream** [tmatilai/vagrant-proxyconf#88]
When switching back and forth between environments with and without a proxy (e.g. work and home), the proxy settings for apt repositories using PPA URIs become invalid.

I can reproduce this by doing the following:
- Provision a new VM without a proxy
- Enable proxy and re-provision
- Disable proxy and re-provision

The last step fails with an error similar to the one below:

```
==> default: ================================================================================
==> default: Error executing action `add` on resource 'apt_repository[php5-5.6]'
==> default: ================================================================================
==> default: RuntimeError
==> default: ------------
==> default:
==> default: Non-HTTP proxy URI:
==> default:
==> default: Cookbook Trace:
==> default: ---------------
==> default: /tmp/vagrant-chef-3/chef-solo-1/cookbooks/apt/providers/repository.rb:109:in `get_ppa_key'
==> default: /tmp/vagrant-chef-3/chef-solo-1/cookbooks/apt/providers/repository.rb:134:in `get_ppa_url'
==> default: /tmp/vagrant-chef-3/chef-solo-1/cookbooks/apt/providers/repository.rb:166:in `block in class_from_file'
==> default:
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /tmp/vagrant-chef-3/chef-solo-1/cookbooks/quasarvm/recipes/default.rb
==> default:
==> default:   5: apt_repository 'php5-5.6' do
==> default:   6:   uri          'ppa:ondrej/php5-5.6'
==> default:   7:   distribution node['lsb']['codename']
==> default:   8: end
==> default:   9:
```

I originally came across this issue when testing possible configuration issues (on my end) related to issue #87.

**Comment by codylane** [comment]
Closing issue, no further information received.
